categories:
  键盘:
    - 键盘
    - 机械键盘
    - 蓝牙键盘
    - 无线键盘
  台灯:
    - 台灯
    - 灯
    - 护眼灯
    - 宿舍灯
  耳机:
    - 耳机
    - 蓝牙耳机
    - 降噪耳机
    - 头戴耳机
  笔记本:
    - 笔记本
    - 笔记本电脑
    - 电脑
    - 轻薄本
  充电宝:
    - 充电宝
    - 移动电源
    - 便携电源
